name: Deploy to GCE
on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Replace with a suitable runner OS if needed

    steps:
      - uses: mattes/gce-deploy-action@v5.0.0
